import { notFound } from 'next/navigation';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { Card, Button, Textarea, Badge, Input } from '@/components/ui';
import { conversationPriorities } from '@/domain/communication/validation';
import { formatDate } from '@/lib/utils';

export default async function Thread({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { tenant, user } = await requireTenantPermission('message.manage');
  const [conversation, team] = await Promise.all([
    db.conversation.findFirst({ where: { id, tenantId: tenant.id }, include: { company: true, participants: { include: { user: true } }, messages: { include: { user: true, attachments: { include: { file: true } } }, orderBy: { createdAt: 'asc' } } } }),
    db.membership.findMany({ where: { tenantId: tenant.id, active: true, user: { active: true } }, include: { user: true }, orderBy: { user: { name: 'asc' } } }),
  ]);
  if (!conversation) notFound();
  await db.conversationParticipant.upsert({ where: { conversationId_userId: { conversationId: id, userId: user.id } }, update: { lastReadAt: new Date() }, create: { conversationId: id, userId: user.id, lastReadAt: new Date() } });
  return <div className="max-w-5xl"><div className="flex flex-wrap justify-between gap-3"><div><a href="/messages" className="text-sm text-brand-700">← Voltar às mensagens</a><h1 className="mt-1 text-2xl font-bold">{conversation.subject}</h1><p className="text-slate-500">{conversation.company?.legalName ?? 'Conversa interna'} · {conversation.category ?? 'Sem categoria'}</p></div><div className="flex gap-2"><Badge>{conversation.priority}</Badge><Badge>{conversation.status}</Badge></div></div>
    <Card className="mt-6"><h2 className="font-bold">Organização da conversa</h2><form action={`/api/conversations/${id}/manage`} method="post" className="mt-3 grid gap-3 md:grid-cols-3"><label className="text-sm font-medium">Situação<select name="status" defaultValue={conversation.status} className="mt-1 w-full rounded-xl border p-2.5">{['NEW','IN_PROGRESS','WAITING_COMPANY','WAITING_CONSULTANT','RESOLVED','ARCHIVED','REOPENED'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Prioridade<select name="priority" defaultValue={conversation.priority} className="mt-1 w-full rounded-xl border p-2.5">{conversationPriorities.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Responsável<select name="assignedToId" defaultValue={conversation.assignedToId ?? ''} className="mt-1 w-full rounded-xl border p-2.5"><option value="">Não atribuído</option>{team.map((member) => <option key={member.userId} value={member.userId}>{member.user.name}</option>)}</select></label><div className="md:col-span-3"><Button>Salvar organização</Button></div></form><p className="mt-3 text-xs text-slate-500">Participantes: {conversation.participants.map((participant) => participant.user.name).join(', ') || 'Nenhum'}{conversation.relatedType ? ` · vínculo: ${conversation.relatedType}` : ''}</p></Card>
    <Card className="mt-6"><div className="space-y-4">{conversation.messages.map((message) => <div key={message.id} className={`max-w-[88%] rounded-2xl p-3 ${message.internal ? 'border border-amber-300 bg-amber-50' : message.userId === user.id ? 'ml-auto bg-brand-600 text-white' : 'bg-slate-100'}`}><div className="flex justify-between gap-3"><p className="text-xs opacity-70">{message.user?.name ?? message.channel}{message.internal ? ' · nota interna' : ''}</p><p className="text-xs opacity-60">{formatDate(message.createdAt)}</p></div><p className="mt-1 whitespace-pre-wrap">{message.body}</p>{message.attachments.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{message.attachments.map((attachment) => <a key={attachment.id} href={`/api/files/local?key=${encodeURIComponent(attachment.file.storageKey)}`} target="_blank" className={`rounded-lg px-2.5 py-1.5 text-xs font-semibold ${message.userId === user.id && !message.internal ? 'bg-white/20 text-white' : 'bg-white text-brand-700'}`}>{attachment.file.originalName}</a>)}</div>}</div>)}</div>
      <form action={`/api/conversations/${conversation.id}/messages`} method="post" encType="multipart/form-data" className="mt-6"><Textarea name="body" required maxLength={20000} rows={4} placeholder="Escreva uma mensagem..."/><div className="mt-2 grid gap-2 md:grid-cols-[1fr_auto]"><Input name="attachments" type="file" multiple /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="internal" value="true"/> Nota interna, invisível para a empresa</label></div><Button className="mt-3">Enviar mensagem</Button></form></Card></div>;
}
