import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireTenantPermission } from '@/lib/auth';
import { db } from '@/lib/db';
import { hasTenantPermission } from '@/lib/rbac';
import { Card, Button, Input, Badge, Textarea } from '@/components/ui';
import { formatDate } from '@/lib/utils';

const statusTone = (status: string): 'neutral' | 'success' | 'warning' | 'danger' => status === 'COMPLETED' || status === 'EFFECTIVENESS_VERIFIED' ? 'success' : status === 'OVERDUE' || status === 'REJECTED' ? 'danger' : status === 'IN_PROGRESS' || status === 'WAITING_VALIDATION' ? 'warning' : 'neutral';

export default async function ActionsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { tenant, membership } = await requireTenantPermission('company.read');
  const canManage = hasTenantPermission(membership.role, 'action.manage', membership.permissions);
  const company = await db.company.findFirst({ where: { id, tenantId: tenant.id }, include: {
    risks: { where: { status: 'ACTIVE' }, orderBy: { code: 'asc' } },
    actionPlans: { include: { items: { include: { risk: true, evidences: { include: { file: true }, orderBy: { createdAt: 'desc' } } }, orderBy: [{ dueDate: 'asc' }, { code: 'asc' }] } }, orderBy: { createdAt: 'desc' } },
  } });
  if (!company) notFound();
  const now = new Date();
  const items = company.actionPlans.flatMap((plan) => plan.items);
  const overdue = items.filter((item) => item.dueDate && item.dueDate < now && !['COMPLETED', 'EFFECTIVENESS_VERIFIED', 'CANCELLED'].includes(item.status));
  const comments = items.length ? await db.entityComment.findMany({ where: { companyId: id, entityType: 'ACTION', entityId: { in: items.map((item) => item.id) } }, include: { user: true, attachments: { include: { file: true } } }, orderBy: { createdAt: 'asc' } }) : [];
  const commentsByAction = new Map<string, typeof comments>();
  for (const comment of comments) commentsByAction.set(comment.entityId, [...(commentsByAction.get(comment.entityId) ?? []), comment]);

  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href={`/companies/${id}`} className="text-sm text-brand-700">← Voltar à empresa</Link><h1 className="mt-1 text-3xl font-bold">Plano de ação 5W2H</h1><p className="text-slate-500">{company.tradeName ?? company.legalName}</p></div><Link href={`/companies/${id}/risks`} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Inventário de riscos</Link></div>
    <div className="mt-6 grid gap-4 md:grid-cols-4"><Card><p className="text-sm text-slate-500">Planos</p><p className="text-3xl font-bold">{company.actionPlans.length}</p></Card><Card><p className="text-sm text-slate-500">Ações</p><p className="text-3xl font-bold">{items.length}</p></Card><Card><p className="text-sm text-slate-500">Vencidas</p><p className="text-3xl font-bold text-rose-700">{overdue.length}</p></Card><Card><p className="text-sm text-slate-500">Eficácia verificada</p><p className="text-3xl font-bold text-emerald-700">{items.filter((item) => item.status === 'EFFECTIVENESS_VERIFIED').length}</p></Card></div>
    {canManage && <Card className="mt-6"><h2 className="font-bold">Novo plano</h2><form action={`/api/companies/${id}/action-plans`} method="post" className="mt-3 grid gap-3 md:grid-cols-4"><label className="text-sm font-medium md:col-span-2">Nome<Input name="name" required placeholder="Plano de ação 2026" /></label><label className="text-sm font-medium">Ano<Input name="year" type="number" min="2000" max="2200" defaultValue={new Date().getFullYear()} /></label><label className="text-sm font-medium">Revisão<Input name="reviewDueAt" type="date" /></label><div className="md:col-span-4"><Button>Criar plano</Button></div></form></Card>}
    <div className="mt-6 space-y-6">{company.actionPlans.map((plan) => <Card key={plan.id}><div className="flex justify-between"><div><h2 className="font-bold">{plan.name}</h2><p className="text-xs text-slate-500">{plan.year ?? 'Sem ano'} · revisão {formatDate(plan.reviewDueAt)}</p></div><Badge>{plan.status}</Badge></div>
      {canManage && <details className="mt-4 rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Adicionar ação</summary><ActionForm action={`/api/action-plans/${plan.id}/items`} risks={company.risks} /></details>}
      <div className="mt-4 space-y-4">{plan.items.map((item) => { const isOverdue = item.dueDate && item.dueDate < now && !['COMPLETED','EFFECTIVENESS_VERIFIED','CANCELLED'].includes(item.status); return <div key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-slate-500">{item.code} · {item.priority ?? 'Sem prioridade'}{item.risk ? ` · ${item.risk.code}` : ''}</p><p className="font-semibold">{item.action}</p><p className="mt-1 text-sm text-slate-500">Responsável: {item.responsible ?? '—'} · Verificador: {item.verifier ?? '—'} · Prazo: {formatDate(item.dueDate)}</p></div><div className="flex gap-2"><Badge tone={isOverdue ? 'danger' : statusTone(item.status)}>{isOverdue ? 'VENCIDA' : item.status}</Badge><Badge>{item.progress}%</Badge></div></div>
        <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-brand-600" style={{ width: `${item.progress}%` }} /></div>
        {item.evidences.length > 0 && <div className="mt-4 space-y-2"><p className="text-sm font-semibold">Evidências</p>{item.evidences.map((evidence) => <div key={evidence.id} className="rounded-xl bg-slate-50 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><div>{evidence.file && <a className="font-medium text-brand-700" href={`/api/files/local?key=${encodeURIComponent(evidence.file.storageKey)}`} target="_blank">{evidence.file.originalName}</a>}<p className="text-xs text-slate-500">{evidence.description ?? 'Sem descrição'}</p></div><Badge tone={evidence.status === 'APPROVED' ? 'success' : evidence.status === 'REJECTED' ? 'danger' : 'warning'}>{evidence.status}</Badge></div>{canManage && <form action={`/api/action-evidences/${evidence.id}/review`} method="post" className="mt-2 flex flex-wrap gap-2"><select name="status" defaultValue={evidence.status} className="rounded-xl border p-2 text-sm"><option value="PENDING">Pendente</option><option value="APPROVED">Aprovar</option><option value="REJECTED">Rejeitar</option></select><Input name="reviewNotes" placeholder="Parecer técnico" className="max-w-md" /><Button>Revisar</Button></form>}</div>)}</div>}
        <div className="mt-4 rounded-xl border p-3"><p className="text-sm font-semibold">Comentários e acompanhamento</p><div className="mt-2 space-y-2">{(commentsByAction.get(item.id) ?? []).map((comment) => <div key={comment.id} className={`rounded-lg p-2.5 text-sm ${comment.internal ? 'border border-amber-200 bg-amber-50' : 'bg-slate-50'}`}><p className="text-xs text-slate-500">{comment.user?.name ?? 'Usuário removido'}{comment.internal ? ' · interno' : ' · visível ao cliente'}</p><p className="whitespace-pre-wrap">{comment.body}</p>{comment.attachments.length > 0 && <div className="mt-2 flex flex-wrap gap-2">{comment.attachments.map((attachment) => <a key={attachment.id} href={`/api/files/local?key=${encodeURIComponent(attachment.file.storageKey)}`} target="_blank" className="text-xs font-semibold text-brand-700">{attachment.file.originalName}</a>)}</div>}</div>)}{!(commentsByAction.get(item.id) ?? []).length && <p className="text-xs text-slate-500">Nenhum comentário.</p>}</div>{canManage && <form action={`/api/companies/${id}/comments`} method="post" encType="multipart/form-data" className="mt-3 grid gap-2"><input type="hidden" name="entityType" value="ACTION"/><input type="hidden" name="entityId" value={item.id}/><input type="hidden" name="returnTo" value={`/companies/${id}/actions`}/><Textarea name="body" required maxLength={5000} rows={2} placeholder="Registrar comentário"/><Input name="attachments" type="file" multiple/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="internal" value="true"/> Comentário interno, invisível para o cliente</label><Button>Adicionar comentário</Button></form>}</div>
        {canManage && <details className="mt-4 rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Editar e validar</summary><ActionForm action={`/api/actions/${item.id}`} risks={company.risks} item={item} /><form action={`/api/actions/${item.id}/evidences`} method="post" encType="multipart/form-data" className="mt-4 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><Input name="file" type="file" required /><Input name="description" placeholder="Descrição da evidência" /><Button>Anexar evidência</Button></form></details>}
      </div>; })}{!plan.items.length && <p className="py-4 text-sm text-slate-500">Nenhuma ação neste plano.</p>}</div>
    </Card>)}{!company.actionPlans.length && <Card><p className="text-sm text-slate-500">Nenhum plano de ação cadastrado.</p></Card>}</div>
  </div>;
}

function ActionForm({ action, risks, item }: { action: string; risks: Array<{ id: string; code: string; hazard: string }>; item?: any }) {
  return <form action={action} method="post" className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
    {!item && <><label className="text-sm font-medium">Código<Input name="code" required placeholder="A-001" /></label><label className="text-sm font-medium">Risco<select name="riskId" className="mt-1 w-full rounded-xl border p-2.5"><option value="">Sem vínculo</option>{risks.map((risk) => <option key={risk.id} value={risk.id}>{risk.code} — {risk.hazard}</option>)}</select></label></>}
    <label className="text-sm font-medium md:col-span-2">O que será feito?<Textarea name="action" required defaultValue={item?.action ?? ''} /></label><label className="text-sm font-medium">Responsável<Input name="responsible" defaultValue={item?.responsible ?? ''} /></label><label className="text-sm font-medium">Verificador<Input name="verifier" defaultValue={item?.verifier ?? ''} /></label><label className="text-sm font-medium">Prazo<Input name="dueDate" type="date" defaultValue={item?.dueDate ? new Date(item.dueDate).toISOString().slice(0,10) : ''} /></label><label className="text-sm font-medium">Prioridade<Input name="priority" defaultValue={item?.priority ?? ''} /></label>
    <label className="text-sm font-medium">Onde?<Input name="location" defaultValue={item?.location ?? ''} /></label><label className="text-sm font-medium">Custo previsto<Input name="estimatedCost" defaultValue={item?.estimatedCost?.toString?.() ?? ''} /></label><label className="text-sm font-medium">Custo real<Input name="actualCost" defaultValue={item?.actualCost?.toString?.() ?? ''} /></label><label className="text-sm font-medium">Progresso (%)<Input name="progress" type="number" min="0" max="100" defaultValue={item?.progress ?? 0} /></label>
    <label className="text-sm font-medium md:col-span-2">Por quê?<Textarea name="reason" defaultValue={item?.reason ?? ''} /></label><label className="text-sm font-medium md:col-span-2">Como?<Textarea name="method" defaultValue={item?.method ?? ''} /></label>
    <label className="text-sm font-medium">Status<select name="status" defaultValue={item?.status ?? 'NOT_STARTED'} className="mt-1 w-full rounded-xl border p-2.5">{['DRAFT','PENDING_APPROVAL','NOT_STARTED','IN_PROGRESS','WAITING_EVIDENCE','WAITING_VALIDATION','COMPLETED','PARTIAL','REJECTED','CANCELLED','OVERDUE','EFFECTIVENESS_VERIFIED'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Resultado da eficácia<Input name="effectivenessStatus" defaultValue={item?.effectivenessStatus ?? ''} placeholder="EFICAZ, PARCIAL..." /></label><label className="text-sm font-medium">Risco residual<select name="residualLevel" defaultValue={item?.residualLevel ?? ''} className="mt-1 w-full rounded-xl border p-2.5"><option value="">Não avaliado</option>{['VERY_LOW','LOW','MODERATE','HIGH','CRITICAL'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Pontuação residual<Input name="residualScore" type="number" min="0" step="0.01" defaultValue={item?.residualScore ?? ''} /></label>
    <label className="text-sm font-medium md:col-span-2">Notas de eficácia<Textarea name="effectivenessNotes" defaultValue={item?.effectivenessNotes ?? ''} /></label><label className="text-sm font-medium">Próxima revisão<Input name="nextReviewAt" type="date" defaultValue={item?.nextReviewAt ? new Date(item.nextReviewAt).toISOString().slice(0,10) : ''} /></label><label className="text-sm font-medium">Motivo do atraso<Input name="delayReason" defaultValue={item?.delayReason ?? ''} /></label>
    <div className="md:col-span-2 xl:col-span-4"><Button>{item ? 'Salvar ação' : 'Adicionar ação'}</Button></div>
  </form>;
}
